### PR TITLE
Feature/166 setup ci with cypress

### PR DESCRIPTION
**Pull request by muganwas**

### CODE REVIEW

**Comment by choshun** [comment]
Can you rebase this?

**Comment by choshun** [comment]
Also if you can have similar changes in one commit?

e.g. `Update node.js.yml`

**Comment by muganwas** [comment]
> Can you rebase this?

I don't have the required access.

**Comment by choshun** [comment]
Required access to rebase local branches?

**Comment by muganwas** [comment]
> Required access to rebase local branches?

Oh my bad, thought you mean on here.

**Comment by choshun** [comment]
Sorry, wasn't sure where you were with git, one last thing, it would be nice to say what the commit is doing functionally - ideally I can read just the titles of the commits from top to bottom and have a very good sense what the PR is doing

**Comment by choshun** [comment]
One step at a time though! Takes practice, I can help you rebase if you want

**Comment by muganwas** [comment]
> One step at a time though! Takes practice, I can help you rebase if you want

No, I've got it.

**Pull request closed without merging**
